"""user_upgrade

Revision ID: caca53cfba21
Revises: aa5e36ac9864
Create Date: 2025-07-30 15:25:11.697765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caca53cfba21'
down_revision: Union[str, Sequence[str], None] = 'aa5e36ac9864'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.Integer(), nullable=False), schema='db_schema')
    op.add_column('users', sa.Column('email', sa.String(length=200), nullable=False), schema='db_schema')
    op.add_column('users', sa.Column('password', sa.String(length=200), nullable=False), schema='db_schema')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password', schema='db_schema')
    op.drop_column('users', 'email', schema='db_schema')
    op.drop_column('users', 'phone', schema='db_schema')
    # ### end Alembic commands ###
